[package]
name = "molly-python"
version = "0.5.1"
edition = "2021"

[lib]
name = "_molly"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"] }
molly = { path = "../.." }
numpy = "0.24.0"
